### ISSUE TITLE
Feature request: add support for solc --contract option

### ISSUE THREAD

**Issue by ddeclerck** [OCamlPro/freeton_wallet#34]
It would be nice to add support for solc --contract option. This allows to set the "main" contract when a Solidity file contains several contracts.

**Comment by lefessan** [comment]
It's not automatically the last one that is supposed to be the one generated ?

**Comment by ddeclerck** [comment]
I'm not sure. Right now solc complains with the following error message :
`Error: Source file contains at least two deployable contracts. Consider adding the option --contract in compiler command line to select the desired contract.`

**Comment by lefessan** [comment]
Done.
