### ISSUE TITLE
Masterchain addresses wrongly parsed as a command line option

### ISSUE THREAD

**Issue by lefessan** [OCamlPro/freeton_wallet#4]
The following example does not work:

```
$ ft account --create myuser2 --address "-1:a3dbe7dbda246199d7af8a361b01eb1313cfa2932029b29133f980b7b51d1bcd" --contract SafeMultisigWallet

ft: unknown option -1'.
Usage: ft account [OPTION]... [ARG]...
Try ft account --help' or `ft --help' for more information.
```

**Comment by lefessan** [comment]
The temporary solution is to use `--address=-1:a3dbe7dbda246199d7af8a361b01eb1313cfa2932029b29133f980b7b51d1bcd` for example.
I am not sure if the issue can easily be fixed, it looks like a problem of Cmdliner, the library used to parse command line options.

**Comment by ddeclerck** [comment]
Another solution could be to add a single-dash option for address, to avoid the extra '=' (but you'd still have to glue the option name with the argument).

**Comment by lefessan** [comment]
Fixed. 

The current solution is to preprocess all options and add a 0 in front of -1:, so that -1:XXX becomes 0-1:XXX. This notation is later recognized as the same as -1:XXX.
