### ISSUE TITLE
Suggestion: Inform user that "not yet created" also means that the balance is zero

### ISSUE THREAD

**Issue by tomsib2001** [OCamlPro/freeton_wallet#42]
(at line https://github.com/OCamlPro/freeton_wallet/blob/39f7955cb9a5f0eff510dfc4409b04bab2694b51/src/freeton_wallet_lib/commandAccount.ml#L100 )
I'm thinking of the following situation. I create an account as in
```
ft account --create toto --surf
```
and then I query the account:
```
ft account toto
Config loaded from /home/thomas/.ft/config.json
Network: nil
Loading wallet file /home/thomas/.ft/nil/wallet.json
Account "toto": not yet created
```
But it isn't immediately apparent that once my account receives money, _even if I haven't deployed the actual contract yet_, this will be mentioned.

**Comment by lefessan** [comment]
It now writes
