### ISSUE TITLE
ft debot --new doesn't work in docker

### ISSUE THREAD

**Issue by NoamDev** [OCamlPro/freeton_wallet#53]
Reproduction Steps:
> docker pull ocamlpro/ft
> wget https://raw.githubusercontent.com/OCamlPro/freeton_wallet/master/docker/ft
> ./ft debot --new=HelloDebot

Calling git clone https://github.com/tonlabs/debots.git
Error: Command 'git clone https://github.com/tonlabs/debots.git' exited with error code 127

**Comment by lefessan** [comment]
Thanks for the issue. I justed pushed a new image. Could you test if it fixes the problem ?

**Comment by NoamDev** [comment]
Yes, thank you! Closing.
