### ISSUE TITLE
Update tonos-cli version in the docker image

### ISSUE THREAD

**Issue by NoamDev** [OCamlPro/freeton_wallet#54]
The tonos-cli version in the docker image (0.13.1) can't actually run the debot template generated by `ft debot --new`.
Latest tonos-cli (tried with 0.17.16) however can run it without error.

**Comment by lefessan** [comment]
The docker image has been updated:
```
ft client -- --version                                          
[...]
Calling /bin/tonos-cli --config /user/.ft/mainnet/tonos-cli.config --version
tonos_cli 0.17.16
COMMIT_ID: e0e718d31e3cb31b365819978e187c4eada75c5b
BUILD_DATE: 2021-08-18 21:44:07 +0000
COMMIT_DATE: 2021-08-18 10:04:24 +0300
GIT_BRANCH: master
```
(from the Nil Foundation repository on Github)

**Comment by NoamDev** [comment]
It seems it still doesn't work. my error is this:
```
Error: Command '/bin/tonos-cli --config /user/.ft/sandbox1/tonos-cli.config debot fetch 0:991855a0b553ea98f6f24d9e71336b63bffed5c1db605ccd189ec31fdb83bfe7' exited with error code SIGNAL -10
```
I guess the problem is not in different version of the code of tonos-cli, but in different version of one of its dependencies, after all nil foundation are using its own forks of some dependencies, see here: https://github.com/tonlabs/tonos-cli/compare/master...NilFoundation:master
Maybe NF's fork of ton-vm needs an update?
I suggest to use tonlabs' builds for the time being to get a stable image and create another for vergroth16 support.

**Comment by NoamDev** [comment]
If you want to stick with NF's build, I suggest to update ton-executor.

**Comment by lefessan** [comment]
So, the current image now contains both toolchains, although `ft` itself is running the TON Labs toolchain (which means it cannot directly call local Nil contracts with `VERGROTH16`, unless using `FT_USE_TONOS=1` to force calling `tonos-cli`). Toolchains are associated to switches, switches have toolchain "" (default) by default, but `ft switch set --toolchain nil` can be used to force the current switch to use Nil's toolchain.
