### ISSUE TITLE
Allow specifying a switch with an enviroment variable

### ISSUE THREAD

**Issue by NoamDev** [OCamlPro/freeton_wallet#68]
Sometimes you might wanna have multiple terminal windows, each working on a different network. It'd be nice to have some FT_SWITCH variable that if set would override the switch selection.

**Comment by lefessan** [comment]
Have you tried it ? It does not work ?

https://github.com/OCamlPro/freeton_wallet/blob/9c2cd2f42cc599dc388278c4491e95a2308729ce/src/freeton_wallet_lib/config.ml#L23

**Comment by NoamDev** [comment]
Haha, I should've just tried. It works, thanks!
